### ISSUE TITLE
Error running action out of the box

### ISSUE THREAD

**Issue by vadi2** [JimCronqvist/action-ssh#1]
I've setup the action as instructed (https://github.com/vadi2/Mudlet/blob/084a29de3021d2c9c882d393ae477c8bb673ec12/.github/workflows/update-geyser-docs.yaml#L33-L38) and while it connected and ran, it didn't do successfully:

```
Run on: ***
Commands:
ls -lah

Connecting to ***...
Welcome to Ubuntu 16.04.6 LTS (GNU/Linux 5.4.10-x86_64-linode132 x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

 * Ubuntu 20.04 LTS is out, raising the bar on performance, security,
   and optimisation for Intel, AMD, Nvidia, ARM64 and Z15 as well as
   AWS, Azure and Google Cloud.

     https://ubuntu.com/blog/ubuntu-20-04-lts-arrives

New release '18.04.4 LTS' available.
Run 'do-release-upgrade' to upgrade to it.

-bash: line 22: syntax error near unexpected token `;;'
```

[Full log here](https://github.com/vadi2/Mudlet/runs/619150396?check_suite_focus=true).

**Comment by vadi2** [comment]
Nice, thanks!

**Comment by JimCronqvist** [comment]
My pleasure! And thanks for the detailed information.
Please let me know if this solves the issue you were experiencing. If it for some reason did not, can you please switch the flag 'debug' to 'true' and send a new log?

**Comment by dgw** [comment]
Isn't it time to tag a new release? Manually using 7737f11 fixed a bash error I saw when adding this to one of my workflows, but obviously that workflow is now stuck at that commit regardless of any new tagged versions.

**Comment by JimCronqvist** [comment]
Yes, you are absolutely right @dgw, a new release has finally been created, hope this helps. Thanks for using the action!
