### ISSUE TITLE
tag new release

### ISSUE THREAD

**Issue by issacg** [JimCronqvist/action-ssh#4]
Hey @JimCronqvist 

Might I ask you to tag a new release?  I try not to leave actions in my workflows pointing to a branch as there's no telling what could change in the future (even if it's been quiet for a long time)

Thanks so much!

**Comment by JimCronqvist** [comment]
Hi @issacg 
I realize that it was quite a while ago since you wrote, but a new release for 1.0.0 has just been tagged, fixing missing support for using a custom ssh port. If you are still using it, hope this helps! :-)
